Repository selsa-inube/inubekit-fullscreennav, pull requests merged in 2024-04, with the labels that each got.

#5 Adjust and export interfaces
  src/FullscreenNav/index.tsx
  src/FullscreenNav/props.ts
  src/FullscreenNav/stories/FullscreenNav.MultiSections.stories.tsx
  src/FullscreenNav/stories/FullscreenNav.WithoutSections.stories.tsx
  src/FullscreenNav/stories/FullscreenNav.stories.tsx
  src/FullscreenNav/styles.js
  src/index.ts
  vite.config.ts
Labels: minor

#6 Add auto publish
  .autorc.json
  .github/workflows/auto-release.yml
  .gitignore
  package.json
Labels: enhancement

#7 Refactor component to use new token structure
  package.json
  src/FullscreenNav/index.tsx
  src/FullscreenNav/styles.js
Labels: major

#8 Update workflow in order to avoid merges with failed builds
  .github/workflows/auto-release.yml
Labels: minor
